version: '2'
services:
  zookeeper:
    image: quay.io/debezium/zookeeper:2.5
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
  kafka:
    image: quay.io/debezium/kafka:2.5
    ports:
    - "9092:9092"
    links:
    - zookeeper
    environment:
      ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,OUTSIDE://localhost:9093
      KAFKA_LISTENERS: INTERNAL://kafka:9092,OUTSIDE://kafka:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      ZOOKEEPER_CONNECT: zookeeper:2181
  mysql_source:
    image: quay.io/debezium/example-mysql:2.5
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: debezium
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: mysqlpw
  connect:
    image: quay.io/debezium/connect:2.5
    ports: 
      - "8083:8083"
    links:
      - mysql_source
      - kafka
    environment:
     - BOOTSTRAP_SERVERS=kafka:9092
     - GROUP_ID=1
     - CONFIG_STORAGE_TOPIC=my_connect_configs
     - OFFSET_STORAGE_TOPIC=my_connect_offsets

  watcher:
    image: quay.io/debezium/kafka:2.5
    ports:
      - "1000:1000"
    links:
    - zookeeper
    - kafka
    environment:
      ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER: kafka:9092
    command: watch-topic -a -k dbserver1.inventory.customers